# Site title
title: "How to do it ..."

# A description of your site for social meta tag and search engines
description: "这个Blog是我的生活日记和学习笔记，文章记录了我在课外学习，日常学校课程里所碰到的问题和解决办法，当然也分享了生活中碰到的各种有趣的事情。"

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://kongpengju.com"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: ""

# The site cover image on the home page
image: 

# The shortname for your Disqus site to enable comments
disqus_shortname:

# Your Google Analytics tracking code
google_analytics_tracking_id: "UA-141495487-1"

# Site navigation
nav:
  - title: "Home"
    url:   "/"
  - title: "Learn Code"
    url:   "/learn_code"
  - title: "About This Site"
    url:   "/about"


# Author information
author:
  name: Tian Tian
  bio: 我是我们家的熄灯小号手....
  avatar: /images/tiantian.png

# The "read next" posts to recommend at the bottom of each post
recommended_posts:
  - url: /blog/2019/07/18/Python-learn-answers_01/
  - url: /blog/2019/07/22/learncodeforpython001/
  - url: /blog/2019/07/21/learnenglisherror/
  - url: /blog/2018/06/21/test_pkts_and_test_kbs/
  - url: /blog/2018/09/14/weiqi_0001_xiaojianhoushi/
  - url: /blog/2019/07/18/irc-chat-with-me/
  - url: /blog/2018/09/17/weiqi_dingshiyihoudexiafa001/
  - url: /blog/2018/09/12/NHK_66th_zhaovswang/

# Extra Open Graph and Twitter Cards settings for social sharing

# Fallback og:image when no page.image or site.image. Facebook requires image be
# at least 200 x 200 pixels.
og_image:

# twitter:site. Your Twitter username without "@"
twitter_site: TTGM_FUN

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-redirect-from
